apiVersion: batch/v1
kind: CronJob
metadata:
  name: helm-idle-cleanup-cronjob
spec:
  timeZone: {{ .Values.cronjob.timeZone }}
  schedule: {{ .Values.cronjob.schedule }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ .Values.authorization.serviceAccountName }}
          imagePullSecrets:
            - name: {{ .Values.image.imagePullSecretName }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: IfNotPresent
              command:
                - "python"
              args:
                - "src/helm_idle_cleaner.py"
